version: '3.8'

services:
  parlant-service:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PLAYWRIGHT_BRIDGE_URL=http://playwright-bridge:5000
    volumes:
      - ./python:/app
      - ../../tmp:/tmp
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - playwright-bridge
    networks:
      - arcanared

  playwright-bridge:
    build:
      context: ./typescript
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PLAYWRIGHT_BRIDGE_PORT=5000
    volumes:
      - ./typescript:/app
      - ../../tmp:/tmp
    networks:
      - arcanared

networks:
  arcanared:
    driver: bridge
